---
version: 1.2
workflows:
  - name: hic-pipeline
    publish: true
    subclass: WDL
    primaryDescriptorPath: /hic.wdl
    testParameterFiles:
      - /dockstore_test_input.json
    filters:
      branches: PIP-1672-dockstore
      tags: 1.11.0
